### ISSUE TITLE
cheating point in excercise is a false friend

### ISSUE THREAD

**Issue by marscher** [thempel/python-tutorial#1]
you overwrite the variable in the loop, so how useful can that be? Eg. you need to store these in a list and concatenate in the end.

**Comment by thempel** [comment]
What do you mean, in the second part? It was supposed to let people skip the cumbersome csv read. If we include more, it's basically almost the solution, no?

**Comment by thempel** [comment]
Thanks for the remark, I added a comment to the cell.
